require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.3
RSpec/NestedGroups:
  Max: 3
RSpec/MessageSpies:
  EnforcedStyle: 'receive'
RSpec/ContextWording:
  Exclude:
    - "spec/support/shared_contexts/*rb"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
Metrics/LineLength:
  Max: 100
